server:
  port: 8001

spring:
  datasource:
    username: shiro
    password: shiro
    url: jdbc:mysql://175.27.243.243:3306/shiro?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
