

spring:
  datasource:
    url: jdbc:mysql://8.142.199.134:3306/shirojwt
    username: root
    password: XNXxnx520
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 175.27.243.243
    port: 6379
    password: 213879

management:
  endpoints:
    web:
      exposure:
        include: beans